### ISSUE TITLE
IndexOutOfBounds Exception - [App Crashes at Closing Tabs ]

### ISSUE THREAD

**Issue by javaman97** [farimarwat/RedBrowser#8]
While closing Tabs the app crashes and getting error as IndexOutOfBounds Exception

Possible Solution: Modify the logic of counting of Closing Tabs  

![image](https://github.com/user-attachments/assets/95a51f47-0617-4ddd-9d5d-9bdfcbf7c268)

**Comment by farimarwat** [comment]
Fixed
